"""add season_type to games

Revision ID: 12016322a77e
Revises: 12e06d48dfb2
Create Date: 2026-09-29 22:57:27.070811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12016322a77e'
down_revision: Union[str, None] = '12e06d48dfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('season_type', sa.String(length=20), nullable=True))
    # CFBD ingestion only ever pulls seasonType=regular
    op.execute("UPDATE games SET season_type = 'regular' WHERE source = 'cfbd'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'season_type')
    # ### end Alembic commands ###