"""add details_fetched_at to players

Revision ID: 12e06d48dfb2
Revises: 68007bef4262
Create Date: 2026-09-24 17:00:12.590860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12e06d48dfb2'
down_revision: Union[str, None] = '68007bef4262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('details_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'details_fetched_at')
    # ### end Alembic commands ###