"""add team_id to player_stats

Revision ID: 68007bef4262
Revises: aef27aa57e95
Create Date: 2026-09-24 13:37:13.485302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68007bef4262'
down_revision: Union[str, None] = 'aef27aa57e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_player_stats_team_id'), 'player_stats', ['team_id'], unique=False)
    op.create_foreign_key(None, 'player_stats', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    # Existing rows only know the player's current team. That's wrong
    # for traded players, but better than null, and every row written
    # from now on gets the team straight from the box score.
    op.execute(
        """
        UPDATE player_stats ps
        SET team_id = p.team_id
        FROM players p
        WHERE ps.player_id = p.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_stats', type_='foreignkey')
    op.drop_index(op.f('ix_player_stats_team_id'), table_name='player_stats')
    op.drop_column('player_stats', 'team_id')
    # ### end Alembic commands ###
    