"""add classification to teams

Revision ID: aef27aa57e95
Revises: a3ea4fb001e5
Create Date: 2026-09-23 22:04:33.303914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aef27aa57e95'
down_revision: Union[str, None] = 'a3ea4fb001e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('classification', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'classification')
    # ### end Alembic commands ###